<!doctype html><html><head><meta charset="utf-8"><style>
@page{margin:32px}body{font-family:DejaVu Sans,sans-serif;color:#17211f;font-size:10px}.header{border-top:8px solid {{ $quotation->company->accent }};padding:18px 0}.logo{width:110px;height:82px;object-fit:contain}.title{text-align:right;font-size:24px;font-weight:bold;color:{{ $quotation->company->accent }}}.meta{width:100%;margin:15px 0 22px}.meta td{vertical-align:top;width:50%}table.items{width:100%;border-collapse:collapse}.items th{background:{{ $quotation->company->accent }};color:#fff;text-align:left;padding:9px 6px}.items td{padding:9px 6px;border-bottom:1px solid #dfe6e2;vertical-align:middle}.product{width:55px;height:55px;object-fit:contain}.totals{width:42%;margin-left:auto;margin-top:15px;border-collapse:collapse}.totals td{padding:6px}.grand{font-size:14px;font-weight:bold;border-top:2px solid #17211f}.footer{position:fixed;bottom:0;width:100%;border-top:1px solid #ddd;padding-top:9px;color:#596560}
</style></head><body>
<table class="header" width="100%"><tr><td><img class="logo" src="{{ public_path($quotation->company->logo_path) }}"></td><td class="title">QUOTATION<br><span style="font-size:11px;color:#555">{{ $quotation->number }}</span></td></tr></table>
<table class="meta"><tr><td><strong>PREPARED FOR</strong><br>{{ $quotation->customer_name }}<br>{{ $quotation->customer_company }}<br>{{ $quotation->customer_address }}<br>{{ $quotation->customer_email }} {{ $quotation->customer_phone }}</td><td style="text-align:right"><strong>{{ $quotation->company->legal_name }}</strong><br>{{ $quotation->company->address }}<br>Date: {{ $quotation->quotation_date->format('d M Y') }}<br>Valid until: {{ $quotation->valid_until->format('d M Y') }}<br>Currency: OMR</td></tr></table>
@if($quotation->subject)<h3>{{ $quotation->subject }}</h3>@endif
<table class="items"><thead><tr><th>S.No</th><th>Product Photo</th><th>Product Description</th><th>Quantity</th><th>Price per Unit</th><th>Total Price</th></tr></thead><tbody>
@foreach($quotation->items as $item)<tr><td>{{ $loop->iteration }}</td><td>@if($item->photo_url)<img class="product" src="{{ $item->photo_url }}">@endif</td><td>{{ $item->description }}</td><td>{{ number_format($item->quantity,3) }}</td><td>OMR {{ number_format($item->unit_price,3) }}</td><td>OMR {{ number_format($item->line_total,3) }}</td></tr>@endforeach
</tbody></table>
<table class="totals"><tr><td>Subtotal</td><td align="right">OMR {{ number_format($quotation->subtotal,3) }}</td></tr><tr><td>VAT ({{ number_format($quotation->vat_rate,0) }}%)</td><td align="right">OMR {{ number_format($quotation->vat_amount,3) }}</td></tr><tr class="grand"><td>Total</td><td align="right">OMR {{ number_format($quotation->total,3) }}</td></tr></table>
<p><strong>Notes & terms</strong><br>{{ $quotation->notes }}<br>{{ $quotation->company->terms }}</p>
<div class="footer">Prepared by {{ $quotation->creator->name }} · {{ $quotation->creator->phone }} · {{ $quotation->creator->email }}</div>
</body></html>
